# P4 Phase5: Product 层英文文案单一来源（便于演示验收与后续维护）
from __future__ import annotations

# --- 详情面板（listing_detail_panel / listing_result_card）---
VIEW_DETAILS = "View details"

DETAIL_SECTION_OVERVIEW = "Overview"
DETAIL_SECTION_EXPLAIN = "Recommendation & explain"
DETAIL_SECTION_SCORE = "Score breakdown"
DETAIL_SECTION_RISK = "Risks & cautions"
DETAIL_SECTION_SOURCE = "Source"

DETAIL_NO_EXPLAIN_SUMMARY = "No explain summary for this run."
DETAIL_NO_REASONS = "No structured recommendation reasons extracted."
DETAIL_NO_SCORE_COMPONENTS = "No score breakdown in response (total score is on the card)."
DETAIL_NO_RISKS = "No major risks flagged in this analysis."
DETAIL_LINK_LISTING = "Open listing link"
DETAIL_WEIGHTED = "Weighted breakdown"
KEY_RECOMMENDATION_REASON = "Key recommendation reason"

# --- 卡片横幅（listing_result_card）---
TOP_PICK_BANNER = ":trophy: **Top pick #%d** — strongest match in your current filtered view."
FEATURED_IN_BATCH = "Featured in this batch"

# --- 全页标签（app_web lab）---
DISPLAY_LABELS: dict[str, str] = {
    "input_section": "Property details",
    "actions_section": "Actions",
    "validation_section": "Validation",
    "validation_intro": "Please fix the following before re-running analysis.",
    "errors_section": "Errors",
    "error_unexpected": "Unexpected error (details below).",
    "overview": "Overview",
    "score": "Property score",
    "decision": "Decision",
    "decision_caption": "High-level recommendation and confidence from the scoring engine.",
    "recommended": "Recommended reasons",
    "concerns": "Concerns",
    "risks": "Risks",
    "next_steps": "Next steps",
    "analysis_detail": "Analysis (structured detail)",
    "user_facing": "Narrative summary",
    "references": "References",
    "contract_risk": "Contract risk",
    "debug_expander": "Technical trace & debug",
    "listing_snapshot": "Listing snapshot",
    "listing_snapshot_caption": "Key facts, model score, and summary (same card pattern as batch).",
    "batch_listing_cards": "All listings",
    "batch_no_rows": "No listings in this batch response.",
    "criteria_section": "Analysis criteria",
    "criteria_empty": "No extra criteria captured (defaults may apply).",
    "batch_criteria_title": "Batch request (criteria snapshot)",
    "p4_filter_sort_title": "Filter & sort",
    "p4_showing_counts": "Showing %d of %d listings (after filters).",
    "p4_no_matches": "No matching listings — adjust filters and try again.",
    "p4_batch_ranking_expander": "Ranking table",
    "p4_batch_results_by_tier": "Results by tier",
    "p4_batch_stats_title": "Result summary",
    "p4_stat_total": "Total analyzed",
    "p4_stat_succeeded": "Succeeded",
    "p4_stat_top": "Top picks",
    "p4_stat_good": "Good matches",
    "p4_stat_review": "Review needed",
    "p4_stat_showing_caption": "Showing %d of %d listings (after filters).",
    "p4_batch_top_picks_title": "Top picks",
    "p4_batch_top_picks_caption": "Up to 3 listings: API order when available, otherwise your current sort.",
    "p4_batch_top_picks_empty": "No top picks in this view — adjust filters or check failed rows.",
    "p4_tier_good": "Good matches",
    "p4_tier_good_empty": "No listings in this section for the current filters.",
    "p4_tier_review": "Review needed",
    "p4_tier_review_empty": "No listings in this section.",
    "p4_batch_debug_bullets": "Listing #%s — debug bullets",
    "idle_analyze_hint": "Use **Load Demo Data** for samples, **Reset Form** to clear, then **Analyze Property**. Invalid inputs appear under **Validation** without crashing the app.",
    "spinner_analyze": "Running analysis…",
    "spinner_batch": "Running batch analysis…",
    "error_no_result": "No result was returned.",
    "score_missing_hint": "No property score for this run.",
    "run_status_failed": "Failed",
    "run_status_ok": "Completed",
    "run_status_partial": "Completed with issues",
    "batch_section_expander": "Batch analysis (POST /analyze-batch)",
    "batch_section_caption": "**Run batch request** uses the **API base URL** from the sidebar and is disabled while **Use local engine** is on. **Run real multi-source analysis** always runs locally (Playwright + engine).",
    "p7_sidebar_title": "Real listings (P7)",
    "p7_sidebar_caption": "Controls **Continue to Analysis** (Agent) and the **Run real multi-source** button. Scraping uses default portal search URLs unless you override in code.",
    "p7_limit_label": "Listings per portal",
    "p7_headless_label": "Headless browser (off = show Playwright window)",
    "p7_persist_label": "Save scraped listings to storage",
    "p7_real_batch_intro": "**Run real multi-source analysis** — uses **Property details** plus last **Agent** intent (if any) for budget / target postcode, then aggregates Rightmove + Zoopla.",
    "p7_real_batch_button": "Run real multi-source analysis",
    "p7_real_batch_help": "Local Playwright + in-process analyze-batch; ignores the API-only batch button above.",
    "p7_real_spinner": "Scraping & analyzing real listings…",
    "p7_real_error": "Real listings run error: %s",
    "p7_debug_caption": "Last real run: sources **%s** · raw **%s** · unique **%s** · analyzed **%s** · **%.2fs**",
    "batch_results_header": "Batch results",
    "batch_comparison_title": "Comparison summary",
    "batch_risk_summary_title": "Risk summary",
    "batch_last_failed": "Last batch request failed: %s",
    "batch_tier_prereq": "Run a batch with at least one property to see tiered results.",
    "na_placeholder": "N/A",
    "unknown_error": "Unknown error",
    # --- P5 Phase5: Agent 层收口（统一状态与文案）---
    "p5_agent_section_title": "Describe Your Rental Needs",
    "p5_agent_section_caption": "English / 中文 / mixed. Rule-based parser (no LLM). **Continue to Analysis** runs **Rightmove + Zoopla** scrape (Playwright) then **analyze-batch** on real listings.",
    "p5_agent_current_step_label": "Current step:",
    "p5_agent_phase_ui_idle": "**Idle** — enter your request, then **Parse Request**.",
    "p5_agent_phase_ui_parsing": "**Parsing** — extracting structured fields from your text.",
    "p5_agent_phase_ui_parsed": "**Parsed** — review the preview, then **Continue to Analysis**.",
    "p5_agent_phase_ui_ready_for_analysis": "**Ready** — form will sync from the preview when you continue.",
    "p5_agent_phase_ui_submitting": "**Submitting** — scraping listings & running **analyze-batch**.",
    "p5_agent_phase_ui_analysis_success": "**Done** — batch results are below; use **View details** on cards.",
    "p5_agent_phase_ui_analysis_error": "**Error** — batch did not complete; see the message above.",
    "p5_agent_phase_ui_fallback": "Unlisted step: **%s**",
    "p5_agent_refinement_available_suffix": "· **Refine Your Search** is available after results (scroll down).",
    "p5_agent_status_parsing": "Parsing your request (rule-based, local only)…",
    "p5_agent_status_submitting": "Scraping **Rightmove** / **Zoopla** and analyzing…",
    "p5_agent_input_label": "Your rental request",
    "p5_agent_input_placeholder": "e.g. 2 bed flat in Shoreditch, max £1400, bills included, 30 min commute to City",
    "p5_agent_input_help": "Single-turn. **Parse Request** → preview → **Continue to Analysis** (syncs form + batch).",
    "p5_agent_parse_button": "Parse Request",
    "p5_agent_parse_help": "Run the rule-based parser (no LLM, no network).",
    "p5_agent_clear_button": "Clear draft",
    "p5_agent_single_turn_note": "Single-turn only — not a chat. Refine text and re-parse as needed.",
    "p5_agent_raw_heading": "Original input",
    "p5_agent_structured_heading": "Structured preview",
    "p5_agent_preview_note": "Few fields detected — **Continue to Analysis** still works using safe numeric defaults.",
    "p5_agent_preview_rich": "Key fields detected — use **Continue to Analysis** to sync the form and run batch.",
    "p5_agent_readiness_heading": "Next step",
    "p5_agent_ready_sparse": "Sparse parse — you can edit **Property details** below or refine your text.",
    "p5_agent_ready_partial": "Looks good — **Continue to Analysis** to run **analyze-batch**.",
    "p5_agent_ready_no": "Review the preview, then **Continue to Analysis**.",
    "p5_agent_ready_yes": "Form matches the last parsed intent. Use **Analyze Property** for single **/analyze** if needed.",
    "p5_agent_ready_banner": "Values applied to **Property details**.",
    "p5_agent_continue_button": "Continue to Analysis",
    "p5_agent_continue_help": "Sync the form, then run local Playwright scrape + **analyze-batch** on aggregated listings (see sidebar limits).",
    "p5_agent_continue_caption": "Results appear under **Batch results** below.",
    "p5_agent_refinement_hint_before_run": "After you run analysis, scroll down to **Agent summary** for **Refine Your Search** suggestions.",
    "p5_agent_spinner_submit": "Scraping listings & running batch analysis…",
    "p5_agent_batch_success": "**Real listings** analyzed — scroll to **Batch results** for cards, Top picks, and filters.",
    "p5_agent_batch_error": "**analyze-batch** failed: %s",
    "p5_agent_after_batch_success": "Open **View details** on any card for the full breakdown.",
    "p5_agent_after_batch_error": "Fix the issue or edit **Property details** / your text, then **Continue to Analysis** again.",
    # --- Agent summary + Refine (Phase4–5) ---
    "p5_agent_insight_title": "Agent summary",
    "p5_agent_insight_caption": "Rule-based explanation (not LLM). Shown after your analysis results.",
    "p5_agent_insight_bullets_heading": "What shaped this outcome",
    "p5_agent_refine_title": "Refine Your Search",
    "p5_agent_refine_caption": "Suggested follow-ups (not a chat). Buttons append a line to **Describe Your Rental Needs**.",
    "p5_agent_refine_quick_actions_blurb": "**Quick actions** — append one line to **Describe Your Rental Needs**, scroll up, then **Parse Request**.",
    "p5_agent_refine_none": "Core fields look complete — adjust filters or edit your text if you want sharper results.",
    "p5_agent_refine_jump_parse": "Remind me to Parse",
    "p5_agent_refine_jump_help": "Shows a reminder under **Describe Your Rental Needs**.",
    "p5_agent_refine_parse_reminder": "Scroll up to **Describe Your Rental Needs** and click **Parse Request**.",
    "p5_refinement_snippet_ok": "Line added — click **Parse Request**, then **Continue to Analysis** when ready.",
}
